name: Bug report
description: Help us fix a problem in WA2DC
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

        Please fill out the form as completely as you can — it helps us reproduce and fix the issue faster.

        **Security/Privacy:** Do **not** post your Discord bot token, WhatsApp QR codes, webhook URLs, phone numbers, or private chat content. Redact sensitive info in logs/screenshots.

        Docs (setup/commands/troubleshooting): https://arespawn.github.io/WhatsAppToDiscord/

  - type: checkboxes
    attributes:
      label: Before you submit
      options:
        - label: I searched existing issues and this hasn't been reported yet.
          required: true
        - label: I'm running the latest release (or the latest commit if running from source).
          required: true
        - label: I understand I must redact secrets/private data from anything I paste.
          required: true

  - type: dropdown
    id: install_method
    attributes:
      label: Installation method
      options:
        - Packaged release (GitHub Releases)
        - Docker
        - Source (npm / node)
        - Other
    validations:
      required: true

  - type: input
    id: wa2dc_version
    attributes:
      label: WA2DC version
      description: Release tag / Docker image tag / `package.json` version (for source builds).
      placeholder: "v2.0.0 / stable / v2.0.1-beta.5"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "Windows 11 / Ubuntu 22.04 / macOS 15"
    validations:
      required: true

  - type: dropdown
    id: arch
    attributes:
      label: CPU architecture
      options:
        - x64 (amd64)
        - arm64
        - armv7
        - Other / Not sure
    validations:
      required: true

  - type: input
    id: node_version
    attributes:
      label: Node.js version
      description: Output of `node -v` (or "N/A" if using a packaged release or Docker).
      placeholder: "v20.11.1"
    validations:
      required: true

  - type: dropdown
    id: baileys_migration
    attributes:
      label: Is this related to the Baileys 7 migration?
      description: For example, issues that started after upgrading to WA2DC v2.x (duplicate channels, reconnect loops, etc.).
      options:
        - "Yes"
        - "No"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: What happened?
      description: A clear and concise description of the problem.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact commands/messages you used and what happened after each step.
      placeholder: |
        1. Start WA2DC
        2. Run `start <contact>` in #control-room
        3. Send a WhatsApp message
        4. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: "What actually happened?"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste the relevant parts of `terminal.log` and/or `logs.txt` (from startup until the issue occurs). Redact private data.
      render: shell
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / screen recording (optional)
      description: Drag-and-drop images/videos here if it helps explain the issue.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context (optional)
      description: Anything else that might help (recent changes, whether it worked before, etc.).
    validations:
      required: false
